### ISSUE TITLE
Hellord on the ZX Spectrum Next

### ISSUE THREAD

**Issue by rocket-matt** [Nakazoto/Hellorld#1]
Not sure how to contact you but here are screenshots of Hellord on the ZX Spectrum Next.  This is a modern retro machine.  I've used an assembler that I've written myself.  The Next uses a modified Z80 and you can see one of its special instructions there (MUL).

![Hellord1](https://github.com/Nakazoto/Hellorld/assets/120468618/7ed4b216-8622-4529-a5f6-82c2cdafc34c)
![Hellord2](https://github.com/Nakazoto/Hellorld/assets/120468618/968f791d-6df1-44fc-8d56-fd826ce4ea9d)
![Hellord3](https://github.com/Nakazoto/Hellorld/assets/120468618/b9a7b771-0385-455a-a703-fa9130b03c0f)
![Hellord4](https://github.com/Nakazoto/Hellorld/assets/120468618/c7466c75-0799-4784-a262-224984ed3d0d)
![Hellord5](https://github.com/Nakazoto/Hellorld/assets/120468618/fe3f2548-18f5-4274-871e-4cf21b1c3adc)

**Comment by Pistoletjes** [comment]
You introduced a new typo: it should be Hellorld! ;)

**Comment by Nakazoto** [comment]
Thank you so much for the submission!
The ZX Spectrum Next is quite cool, but one thing I'm trying to avoid is emulation. The Z80 in it is fully emulated in an FPGA, which kind of goes against the desire for real deal unique hardware.
Also, as Pistoljetes said, you made a new typo on my old typo, haha!
