### ISSUE TITLE
Hellorld for SC/MP

### ISSUE THREAD

**Issue by mhaardt** [Nakazoto/Hellorld#2]
I don't know how to submit entries, but here is mine (see end of the page):

http://www.moria.de/tech/scmp/hexio/

The SC/MP is an early microprocessor featured in an Elektor series from the end of the 70s. The NDR Klein Computer is a modular DIY system from the early 80s, comparable to S100, ECB and RC2014 systems, featured in a German educational TV series and in the magazine mc microcoputer. What you see is a new edition of the HEXIO and CPU card of the Elektor system adapted to the NDR Klein Computer bus. If you load the hex code using the monitor program and run it: Hellorld

The odd looking string are the bits set in the 7 segment display, loaded directly at address 0x700-0x707 (from right to left). There is no space for the exclamation mark. You skipped two characters, so let me skip another one. :)

**Comment by Nakazoto** [comment]
Very cool! Thank you for the submission!
I think I got it all up correctly:
https://github.com/Nakazoto/Hellorld/wiki/Microcomputers#ndr-klein-with-scmp
