### ISSUE TITLE
Hellord! on Omen Alpha

### ISSUE THREAD

**Issue by Kulicheg** [Nakazoto/Hellorld#3]
Hellord! on Omen Alpha SBC upgraded for CP/M (https://github.com/omenmicro/alpha)
![IMG_20231024_224741](https://github.com/Nakazoto/Hellorld/assets/41168303/a1fc93c9-9b0b-4e66-a4de-7509f096ba5d)
![terminal](https://github.com/Nakazoto/Hellorld/assets/41168303/f8305336-534a-4ba4-82d2-ecb6cf2ca4c2)
![code](https://github.com/Nakazoto/Hellorld/assets/41168303/d42eb3d2-4da6-4306-9fa9-b0fc01096825)
[src.txt](https://github.com/Nakazoto/Hellorld/files/13126801/src.txt)

```
            .ORG    8000h 
START:               
            LXI     H,MESSAGE 
            CALL    TXTOUT 
            HLT      

TXTOUT:              
            CALL    WAITOUT 
            MOV     A,M 
            ANI     07Fh
            OUT     0DFh 
            MOV     A,M 
            ANI     80h 
            RNZ      
            INX     H 
            JMP     TXTOUT 
WAITOUT:             
            IN      0DEh 
            ANI     02h 
            JZ      WAITOUT 
            RET      
MESSAGE:             
            .ISTR   "HELLORD!"
```
			
			
```
8000	21 1F 80 CD 07 80 76 CD 17 80 7E E6 7F D3 DF 7E
8010	E6 80 C0 23 C3 07 80 DB DE E6 02 CA 17 80 C9 48
8020	45 4C 4C 4F 52 44 A1 00 00 00 00 00 00 00 00 00
```

**Comment by Nakazoto** [comment]
Took me bloody forever, but I got the Omen Alpha added in!
Thanks for the submission!
https://github.com/Nakazoto/Hellorld/wiki/Homebrew-Computers#kulichegs-omen-alpha
