### ISSUE TITLE
Hellorld! on Motorola HC11 Microcontroller

### ISSUE THREAD

**Issue by ksteinhaus** [Nakazoto/Hellorld#4]
Hellorld! on a home brew board utilizing a Motorola 68HC11 microcontroller.  I hand wired this board back in 1995, in ROM is the BUFFALO monitor that has a built in assembler / disassembler.  Output is via RS232

![IMG_1738](https://github.com/Nakazoto/Hellorld/assets/149010184/11412e51-375f-4ab6-90eb-c77aec067e5f)

![Screen Shot 2023-10-25 at 2 12 20 PM](https://github.com/Nakazoto/Hellorld/assets/149010184/01002162-d5e2-4294-ac73-00065e4b8ca3)

![Screen Shot 2023-10-25 at 2 07 32 PM](https://github.com/Nakazoto/Hellorld/assets/149010184/d4f2c8b9-5221-4c3c-be91-2d2e8e157e5e)

![Screen Shot 2023-10-25 at 2 09 33 PM](https://github.com/Nakazoto/Hellorld/assets/149010184/5d2616e4-6f52-44ea-a1f8-2b5ec5823b6a)

**Comment by Nakazoto** [comment]
Took me forever, but I got the entry up!
Thank you!
https://github.com/Nakazoto/Hellorld/wiki/Homebrew-Computers#ksteinhaus-68hc11
